#!/bin/sh

LABNAME="mlvpn"
cd "$(dirname "$(readlink -f "$0")")"
. ../common/lab-setup

spawn vm R1 networks 1,2
spawn vm R2 networks 1,3
spawn vm C1 network 2
spawn vm C2 network 3

run
# Executed on each VM
modprobe tun

case $uts in
    R1)
        ip addr add 10.100.1.1/24 dev eth0
        ip addr add 10.10.1.1/24 dev eth1
        sysctl -w net.ipv4.ip_forward=1
        echo ~/Programmes/mlvpn/src/mlvpn -c /home/ed/Programmes/mlvpn/test/lab.R1.conf --user ed --debug -v
        ;;
    R2)
        ip addr add 10.100.1.2/24 dev eth0
        ip addr add 10.10.2.1/24 dev eth1
        sysctl -w net.ipv4.ip_forward=1
        echo ~/Programmes/mlvpn/src/mlvpn -c /home/ed/Programmes/mlvpn/test/lab.R2.conf  --user ed --debug -v
        ;;
    C1)
        ip addr add 10.10.1.2/24 dev eth0
        ip route add default via 10.10.1.1
        #service nginx
        echo "nginx on C2 (R1->R2->C2): http://10.10.2.2"
        ;;
    C2)
        ip addr add 10.10.2.2/24 dev eth0
        ip route add default via 10.10.2.1
        #service nginx
        echo "nginx on C2 (R2->R1->C1): http://10.10.1.2"
        ;;
esac
